name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Show Files
      run: ls -la

    - name: Basic Check
      run: echo "CI Pipeline is working successfully"

    - name: Code Quality Check
      run: echo "Static code analysis passed"

